Sprint 07
aleksB2B/MovieQuiz pull request #4
Opened 2024-08-31 08:32 UTC by aleksB2B

2024-08-31 09:15 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        guard let startTime = startTime, let endTime = endTime else { return }
Было бы хорошо убрать переменные `startTime`, `endTime`, `correctPercent` и `endTimestamp`, так как они не используются дальше

2024-08-31 09:35 UTC, Kirchberg commented on MovieQuizTests/MoviesLoaderTests.swift
> +        waitForExpectations(timeout: 3)
⚠️ Не был использован `StubNetworkClient(emulateError: false)` и не проверено успешное получение данных через `XCTAssert`. Например, можно проверить, сколько нам пришло item'ов или проверить какое-нибудь поле у одного из item'ов

2024-08-31 09:38 UTC, Kirchberg commented on MovieQuiz/Services/NetworkClient.swift
> +}
Целесообразно структуру поместить внутри теста `MovieLoaderTests`, так как она используется только в нем и нигде больше, а при возникновении новых Unit-тестов приходится расширять структуру рядом с основной реализацией или создавать новую в зависимости от необходимости

2024-08-31 09:39 UTC, Kirchberg commented on MovieQuiz/Services/NetworkClient.swift
> +    case test
Не забывай следить за отступами, общепринятые отступы помогают читать код быстрее. 
В общем случае поможет выделить весь файл `cmd+A` и зажать `control+i`

2024-08-31 09:43 UTC, Kirchberg commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    private weak var viewController: MovieQuizViewControllerProtocol?
⚠️ В данном случае лучше не назначать `viewController` типом `MovieQuizViewControllerProtocol`, так как все, что нужно `AlertPresenter` вызвать показ алерта через `viewController`, мы не будем использовать методы протокола `MovieQuizViewControllerProtocol`. Стоит оставить `UIViewController`

2024-08-31 09:43 UTC, Kirchberg commented on MovieQuiz/Presentation/AlertPresenter.swift
> +        let action = UIAlertAction(title: model.buttonText, style: .default) { [weak self] _ in
`Variable 'self' was written to, but never read`

2024-08-31 09:51 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    private var alertPresenter: AlertPresenterProtocol?
⚠️ `alertPresenter` необходимо использовать внутри `MovieQuizViewController` с уже подготовленной моделью `AlertModel`, которую мы формируем в `MovieQuizPresenter`. То есть необходимо сделать следующее: создаем модель `AlertModel` на уровне `MovieQuizPresenter`, потом мы вызываем метод по показу алерта через `MovieQuizViewControllerProtocol`, например `showMessage(with model: AlertModel)` и уже внутри `MovieQuizViewController` вызываем `AlertPresenterProtocol` с передачей уже готовой модели

2024-08-31 09:57 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    private var statisticService: StatisticServiceProtocol = StatisticService()
⚠️ Для большей гибкости и удобства поддержки кода лучше избегать прописывания реализации непосредственно внутри конкретной сущности. Протоколы позволяют передавать любую сущность, скрывая её реализацию, что делает код более заменяемым и универсальным.

2024-08-31 09:58 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        self.questionFactory = QuestionFactory(moviesLoader: MoviesLoader(), delegate: self)
⚠️ Реализацию `QuestionFactory` также стоит передавать извне через `init`

2024-08-31 10:06 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
>          activityIndicator.startAnimating()
Сейчас индикатор загрузки у нас не пропадает при показе следующего вопроса, это видно [на этом скриншоте](https://ibb.co/4fRVzCy)

Рекомендую посмотреть на свойство [hidesWhenStopped](https://developer.apple.com/documentation/uikit/uiactivityindicatorview/1622837-hideswhenstopped) у `activityIndicator`, и использовать его вместо ручного управления свойством `isHidden`. 

Когда ты будешь вызывать `startAnimating` – индикатор будет появляться автоматически, соответственно на `stopAnimating` – скрываться, а свойство `isHidden` больше не понадобится, индикатор все сделает за тебя. 

**Важно:** это свойство настраивают всего раз раз: кодом во `viewDidLoad()` или аналогичной галочкой у элемента на сториборде.
А строки `activityIndicator.isHidden = false(true)` нужно будет убрать

2024-08-31 10:07 UTC, Kirchberg commented on MovieQuiz/Services/MoviesLoader.swift
> +      }
Реализацию в данном случае стоит не оставлять дефолтной

Также не забывай следить за отступами, общепринятые отступы помогают читать код быстрее. 
В общем случае поможет выделить весь файл `cmd+A` и зажать `control+i`

2024-08-31 10:10 UTC, Kirchberg commented on MovieQuizTests/MovieQuizPresenterTests.swift
> +        XCTAssertEqual(viewModel.text, "Question Text") // проверка текста вопроса
⚠️ По условию задания необходимо также проверить, что счетчик вопроса «1/10»

2024-08-31 10:13 UTC, Kirchberg commented on MovieQuizUITests/MovieQuizUITests.swift
> +        XCTAssertEqual(indexLabel.label, "2/10", "The question index should update to '2/10' after tapping 'Нет'")
Было бы хорошо данную проверку также поместить внутри теста `testYesButton`

2024-08-31 10:14 UTC, Kirchberg commented on MovieQuizUITests/MovieQuizUITests.swift
> +            XCTAssertTrue(noButton.waitForExistence(timeout: 5), "No button should be visible before tapping.")
Стоит использовать в данном случае `sleep(5)` для того, чтобы пройтись по всем вопросам

2024-08-31 10:17 UTC, Kirchberg commented on MovieQuizUITests/MovieQuizUITests.swift
> +        restartButton.tap()
В данном тесте это не требуется, так как мы не проверяем смогли ли мы нажать на кнопку перезапуска или проверяем состояние после нажатия кнопки

2024-08-31 10:18 UTC, Kirchberg commented on MovieQuizUITests/MovieQuizUITests.swift
> +//        print("Question label text after reset: \(questionLabelText)")
Данный код стоит удалить, так как он закомментирован

2024-08-31 10:32 UTC, Kirchberg requested changes
Привет, хорошая работа! Есть критические замечания, которые необходимо поправить, отметил их как ⚠️, а также написал об этом в общем отзыве. Буду ждать исправлений, нужно поправить немного :)

2024-09-01 13:50 UTC, aleksB2B commented on MovieQuiz/Services/NetworkClient.swift
> +    case test
За это спасибо:)

2024-09-07 15:58 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        )
⚠️ Передача `self` в конструкторе `QuestionFactory` не нуждается, так как `delegate` настраиваем в `MovieQuizPresenter`.

В данном случае ожидается, что `questionFactory` не хранится как переменная в `MovieQuizViewController` и контроллер не подписан под протокол `QuestionFactoryDelegate`, а `MovieQuizPresenter` подписан под протоколом `QuestionFactoryDelegate` и содержит реализацию этих методов.

В данном случае код, который отрисовывает UI не должен знать про бизнес-логику: `didLoadDataFromServer`, `didFailToLoadData`. Его задача – только передавать сигналы presenter при взаимодействии пользователей с UI и получать сигналы от других сущностей (например, через `AlertPresenterProtocol`) для отображения элементов.

2024-09-07 16:01 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    }
⚠️ Передача `self` в конструкторе `QuestionFactory` не нуждается, так как `delegate` настраиваем в `MovieQuizPresenter`.

В данном случае ожидается, что `questionFactory` не хранится как переменная в `MovieQuizViewController` и контроллер не подписан под протокол `QuestionFactoryDelegate`, а `MovieQuizPresenter` подписан под протоколом `QuestionFactoryDelegate` и содержит реализацию этих методов.

В данном случае код, который отрисовывает UI не должен знать про бизнес-логику: `didLoadDataFromServer`, `didFailToLoadData`. Его задача – только передавать сигналы presenter **при взаимодействии пользователей с UI** и получать сигналы от других сущностей (например, через `AlertPresenterProtocol`) для отображения элементов.

2024-09-07 16:03 UTC, Kirchberg commented on MovieQuizTests/MovieQuizPresenterTests.swift
> +}
Не используется в коде ниже

2024-09-07 16:10 UTC, Kirchberg requested changes
Привет, необходимо исправить один оставшийся критический комментарий, осталось совсем чуть-чуть

2024-09-08 10:09 UTC, Kirchberg approved these changes
Approve ✨

2024-09-10 04:11 UTC, merged